site_name: Hourly

nav:
  - Home: index.md
  - Tutorial: README.ipynb
  - WorkLog.md: WorkLog.md

theme: readthedocs

use_directory_urls: false

plugins:
  - mknotebooks
  - search

markdown_extensions:
  - codehilite
  - admonition
  - markdown_include.include