site_name: Hourly

nav:
  - Home: index.md
  - WorkLog.md: WorkLog.md
  - API: README.ipynb
  - Author's notes: about.md

theme: material

use_directory_urls: false

plugins:
  - mknotebooks
  - search

markdown_extensions:
  - toc:
      permalink: "#"
  - codehilite
  - admonition
  - markdown_include.include

