site_name: Hourly

nav:
  - Home: index.md
  - WorkLog.md: WorkLog.md
  - API: README.ipynb
  - Payments: btcpayserver.md
  - Compensation: Compensation.md
  - FAQ: FAQ.md
  - Author's notes: about.md
  - Press release: press-release.md

theme: material

use_directory_urls: false

plugins:
  - mknotebooks
  - search

markdown_extensions:
  - toc:
      permalink: "#"
  - codehilite
  - admonition
  - markdown_include.include

